parameters:
#    net7_korbo_api.example.class: Net7\KorboApiBundle\Example

services:
#    net7_korbo_api.example:
#        class: %net7_korbo_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
